# Generated by Django 4.2.23 on 2025-08-04 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sricrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sricrm.organization'),
        ),
    ]
