# Generated by Django 4.2.23 on 2025-08-04 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sricrm', '0002_alter_users_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sricrm.organization'),
        ),
        migrations.AlterField(
            model_name='users',
            name='org_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
