# Generated by Django 4.2.23 on 2025-08-05 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sricrm', '0004_alter_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com', to='sricrm.organization'),
        ),
    ]
