# Generated by Django 4.2.23 on 2025-08-05 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sricrm', '0005_alter_company_org'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='org_type',
            new_name='role',
        ),
    ]
